import { Product } from './types';

export const TELEGRAM_BOT_TOKEN = import.meta.env.VITE_TELEGRAM_BOT_TOKEN || "8535410037:AAHxKRQVxe_C25DKgfR9I4VSLr1IQTsCX88";
export const TELEGRAM_CHAT_ID = import.meta.env.VITE_TELEGRAM_CHAT_ID || "8614222741";
export const EXCHANGE_RATE = 50;
export const CASH_FEE_EGP = 5;
export const VODAFONE_NUMBER = "01002240615";
export const VODAFONE_QR_URL = "https://i.ibb.co/fVzgvLrW/Vodafone-logo1.png";
export const BINANCE_ID = "1017392350";
export const BINANCE_QR_URL = "https://i.ibb.co/TM2f81k6/0x0.png";
export const INSTAPAY_NUMBER = "01156003509";
export const INSTAPAY_LOGO_URL = "https://i.ibb.co/WpKtLSBV/000.png";
export const PAYPAL_LINK = "https://paypal.me/walidsala7?locale.x=ar_EG&country.x=EG";
export const PAYPAL_LOGO_URL = "https://i.ibb.co/PsVsf1xN/paypal.png";
export const WHATSAPP_LINK = "https://wa.me/201002240615";

export const productsData: Product[] = [
    { id: 5, name: "DFT Pro Tool", priceUsd: 3, duration: "48 hours", image: "https://i.ibb.co/7t8DFxkF/dft-pro-tool.png", category: 'rent', sortOrder: 1 },
    { id: 8, name: "Unlock Tool", priceUsd: 1, duration: "6 hours", image: "https://i.ibb.co/b52htYz1/fdg.png", category: 'rent', sortOrder: 2 },
    { id: 3, name: "TSM Tool", priceUsd: 1, duration: "12 hours", image: "https://i.ibb.co/r2xLTz9n/as.png", category: 'rent', sortOrder: 3 },
    { id: 2, name: "Android Multi Tool", priceUsd: 1, duration: "3 hours", image: "https://i.ibb.co/dszpmdjm/zx.png", category: 'rent', sortOrder: 4 },
    { id: 12, name: "RENT EFT PRO", priceUsd: 4, duration: "1 hours", image: "https://i.ibb.co/WWnrdFxS/WAD.png", category: 'rent', sortOrder: 5 },
    { id: 13, name: "arab frp", priceUsd: 1, image: "https://i.ibb.co/9m7Yzm2J/ZXX.png", category: 'rent' },
    { id: 22, name: "CM2 Dongle Rent (Version 1.58 )", priceUsd: 2, duration: "30 minutes", image: "https://i.ibb.co/HLDfbpHs/cm2.png", category: 'rent' },
    { id: 11, name: "Anonyshu Tool Rent", priceUsd: 3, duration: "12 hours", image: "https://i.ibb.co/HfVx4wQV/vc.png", category: 'rent' },
    { id: 1, name: "MDM FIX TOOL", priceUsd: 3, duration: "6 hours", image: "https://i.ibb.co/jZGj42qP/Capture.png", category: 'rent' },
    { id: 7, name: "CF Tools", priceUsd: 3, image: "https://i.ibb.co/N6mZrmj5/ww.png", category: 'rent' },
    { id: 9, name: "AndroidWinTool", priceUsd: 3, image: "https://i.ibb.co/n8PRngM7/ASDAS.png", category: 'rent' },
    { id: 15, name: "TFM Tool Pro", priceUsd: 3, duration: "6 hours", image: "https://i.ibb.co/Z1BQrwcd/ASWA.png", category: 'rent' },
    { id: 17, name: "Griffin Unlocker Tool RENT", priceUsd: 3, duration: "6 hours", image: "https://i.ibb.co/Fqy41HQn/RF.png", category: 'rent' },
    { id: 14, name: "Hydra Tool", priceUsd: 4, duration: "24 hours", image: "https://i.ibb.co/mVKsYxm0/DSFDSFSDF.png", category: 'rent' },
    { id: 21, name: "T-TOOL PRO", priceUsd: 4, duration: "6 hours", image: "https://i.ibb.co/C5znJK1G/image.png", category: 'rent' },
    { id: 10, name: "E-GSM Rent", priceUsd: 5, image: "https://i.ibb.co/HT0NFsdJ/SDADA.png", category: 'rent' },
    { id: 18, name: "RENT FRT TOOL", priceUsd: 5, image: "https://i.ibb.co/6RWmFLx3/GHFHF.png", category: 'rent' },
    { id: 6, name: "SamsungTool.us", priceUsd: 8, duration: "12 hours", image: "https://i.ibb.co/kghhQB2b/ASDSADAF.png", category: 'rent' },
    { id: 19, name: "Pandora tool Rent", priceUsd: 10, duration: "48 hours", image: "https://i.ibb.co/tPLP47Mg/GFHHFH.png", category: 'rent' },
    { id: 102, name: "Android Multi Tool Credit", priceUsd: 1.30, image: "https://i.ibb.co/dszpmdjm/zx.png", category: 'credit' },
    { id: 103, name: "TSM Tool Credit", priceUsd: 1.30, image: "https://i.ibb.co/r2xLTz9n/as.png", category: 'credit' },
    { id: 111, name: "Anonyshu Tool Credit", priceUsd: 1.30, image: "https://i.ibb.co/HfVx4wQV/vc.png", category: 'credit' },
    { id: 107, name: "CF Tools Credit", priceUsd: 1.30, image: "https://i.ibb.co/N6mZrmj5/ww.png", category: 'credit' },
    { id: 109, name: "AndroidWinTool Credit", priceUsd: 1.30, image: "https://i.ibb.co/n8PRngM7/ASDAS.png", category: 'credit' },
    { id: 115, name: "TFM Tool Pro Credit", priceUsd: 1.30, image: "https://i.ibb.co/Z1BQrwcd/ASWA.png", category: 'credit' },
    { id: 114, name: "Hydra Tool Credit", priceUsd: 1.30, image: "https://i.ibb.co/mVKsYxm0/DSFDSFSDF.png", category: 'credit' },
    { id: 110, name: "E-GSM Credit", priceUsd: 0.15, image: "https://i.ibb.co/HT0NFsdJ/SDADA.png", category: 'credit', minQty: 10, maxQty: 100 },
    { id: 106, name: "SamsungTool.us Credit", priceUsd: 1.30, image: "https://i.ibb.co/kghhQB2b/ASDSADAF.png", category: 'credit', minQty: 10, maxQty: 10000 },
    { id: 120, name: "Phoenix Service Tool - Credit", priceUsd: 1.30, image: "https://i.ibb.co/1t5FmvZP/image.png", category: 'credit' },
    { id: 104, name: "chimera tool Credit", priceUsd: 1.30, image: "https://i.ibb.co/PZpB3tkX/chimera.png", category: 'credit' },
    { id: 201, name: "Ready Apple ID Without 2FA", priceUsd: 3.30, image: "https://i.ibb.co/0yjrk1k4/image.png", category: 'server' },
    { 
      id: 202, 
      name: "شراء ملفات من حلب تك", 
      nameEn: "Buy files from halab Tech", 
      priceUsd: 1.50, 
      image: "https://i.ibb.co/1f4ffTS6/image.png", 
      category: 'server',
      tooltip: "1GB: 1.50$ | 3GB: 2.50$ | 4GB: 3.30$ | 9GB: 4.20$ | 13GB: 4.75$ | 30GB: 7$",
      sizeOptions: [
        "1MB to 1GB",
        "2GB to 3GB",
        "3GB to 4GB",
        "5GB to 9GB",
        "9GB to 13GB",
        "13GB to 30GB"
      ],
      sizePrices: {
        "1MB to 1GB": 1.50,
        "2GB to 3GB": 2.50,
        "3GB to 4GB": 3.30,
        "5GB to 9GB": 4.20,
        "9GB to 13GB": 4.75,
        "13GB to 30GB": 7.00
      }
    },
    { 
      id: 203, 
      name: "Honor FRP Key - Google Account Removal", 
      priceUsd: 32, 
      image: "https://i.ibb.co/Pvz6s6s0/honor-frp.png", 
      category: 'server',
      requiresSN: true,
      tooltip: "1-30Min Available Slot | Max 1-6 Hrs | Few Time Fast Manually. Note: no cancellation if delayed, no refund for wrong code, no video proof accepted, no investigation, no refund for double imei, no refund for junk or test imei. Huawei ID & HONOR ID Not Supported.",
      downloadLink: "https://mega.nz/file/LcdwzDjS#o-ep7wL3KG--TejTD0Yu3eYQFLiZH4O1g-s-98T3pNE"
    },
];

export const translations = {
    ar: {
        title: "إيجار أدوات السوفت وير",
        subtitle: "خدمات Walid Sala7 - الأفضل والأسرع",
        rentalsTab: "إيجار الأدوات",
        creditsTab: "كريديت للأدوات",
        serverTab: "خدمات السيرفر",
        ordersTab: "سجل الطلبات",
        statusPending: "جاري المعالجة",
        statusAccepted: "مقبول",
        statusRejected: "مرفوض",
        searchPlaceholder: "ابحث عن أداة...",
        searchOrdersPlaceholder: "ابحث برقم الطلب أو اسم الأداة...",
        searchButton: "بحث",
        orderCodeLabel: "كود الطلب الخاص بك:",
        copyCode: "نسخ الكود",
        rentNow: "أحجز الآن",
        priceLabel: "السعر:",
        currency: "ج.م",
        rights: "جميع الحقوق محفوظة",
        paymentTitle: "طرق الدفع المتاحة",
        vodafone: "فودافون كاش",
        binance: "بينانس (USDT)",
        instapay: "إنستا باي (InstaPay)",
        paypal: "باي بال (PayPal)",
        copy: "نسخ",
        copied: "تم النسخ!",
        selectPayment: "تأكيد تفاصيل الإيجار",
        binanceIdLabel: "معرف الدفع (Pay ID)",
        vodafoneNumberLabel: "رقم التحويل",
        confirmOrder: "تأكيد الطلب",
        instructionBinance: "انسخ الـ ID وأتمم الدفع في تطبيق Binance",
        instructionVodafone: "حول المبلغ للرقم أعلاه (يشمل 5 ج.م رسوم)",
        instructionInstapay: "حول المبلغ لرقم إنستا باي أعلاه",
        instructionPaypal: "اضغط على الزر أعلاه لإتمام الدفع عبر PayPal",
        ultraId: "ID الخاص بـ UltraViewer",
        ultraPass: "Password الخاص بـ UltraViewer",
        anyDeskId: "ID الخاص بـ AnyDesk",
        remoteMethod: "اختر أداة التحكم عن بعد",
        paymentMethod: "اختر وسيلة الدفع",
        senderPhonePlaceholder: "اكتب رقم الهاتف الذي حولت منه",
        binanceTxPlaceholder: "اكتب رقم العملية أو اسم حسابك",
        whatsappNumberLabel: "رقم الواتساب (لإرسال اليوزر والباص)",
        whatsappNumberPlaceholder: "ادخل رقم الواتساب الخاص بك",
        preOrderAlert: "تنبيه: قم بالتحويل أولاً قبل الضغط على تأكيد الطلب",
        verifying: "جاري التحقق...",
        waitOwner: "يرجى الانتظار حتى يتم تأكيد التحويل من قبل المالك",
        cancelProcess: "إلغاء العملية",
        accepted: "تم قبول طلبك بنجاح!",
        acceptedMsg: "تم تأكيد الدفع، جاري معالجة طلبك.",
        rejected: "لم يتم تحويل المبلغ لذالك تم رفض طلبك",
        rejectedMsg: "يرجى التأكد من التحويل والمحاولة مرة أخرى أو التواصل معنا.",
        backToStore: "العودة للمتجر",
        close: "إغلاق",
        usd: "بالدولار",
        egp: "بالمصري",
        darkMode: "ليلي",
        lightMode: "نهاري",
        dir: "rtl",
        productLabel: "المنتج",
        totalUsd: "الإجمالي (USD)",
        rateLabel: "سعر الصرف",
        quantityLabel: "الكمية",
        emailLabel: "البريد الإلكتروني",
        snLabel: "ادخل رقم SN",
        helpText: "هل تحتاج مساعدة؟ تواصل معنا عبر واتساب",
        islamicHeader: "بسم الله الرحمن الرحيم - وَقُل رَّبِّ زِدْنِي عِلْمًا",
        hero: "حلول ذكية",
        heroHighlight: "لهاتفك",
        heroSub: "خدمات احترافية، استئجار أدوات السوفت وير، شحن كريديت، وخدمات السيرفر بأفضل الأسعار وأعلى جودة.",
        festiveGreeting: "أعاده الله علينا وعليكم بالخير واليمن والبركات. كل عام وأنتم بخير ❤️",
        homeTab: "الرئيسية",
        ordersHistoryTab: "سجل الطلبات",
        supportTab: "الدعم الفني",
        adminTab: "لوحة الإدارة",
        adminLoginTitle: "تسجيل الدخول للوحة الإدارة",
        adminPasswordLabel: "كلمة المرور",
        adminPasswordPlaceholder: "أدخل كلمة المرور...",
        adminLoginButton: "دخول",
        adminIncorrectPassword: "كلمة المرور غير صحيحة!",
        adminLogoutButton: "تسجيل الخروج",
        adminPanelTitle: "لوحة تحكم المدير",
        adminManageProducts: "إدارة الأدوات",
        adminManageOrders: "إدارة الطلبات",
        adminAddProduct: "إضافة أداة جديدة",
        adminEditProduct: "تعديل أداة",
        adminDeleteProduct: "حذف أداة",
        adminProductNameAr: "اسم الأداة (بالعربية)",
        adminProductNameEn: "اسم الأداة (بالإنجليزية)",
        adminProductPrice: "السعر (USD)",
        adminProductDuration: "المدة (مثال: 6 ساعات)",
        adminProductImage: "رابط الصورة",
        adminProductCategory: "القسم",
        adminProductAvailable: "متاحة للعملاء",
        adminProductUnavailable: "غير متاحة حالياً",
        adminProductStatus: "حالة التوفر",
        adminSaveButton: "حفظ",
        adminCancelButton: "إلغاء",
        adminDeleteConfirm: "هل أنت متأكد من حذف هذه الأداة؟",
        unavailableBadge: "غير متوفر"
    },
    en: {
        title: "Software Tool Rentals",
        subtitle: "Walid Sala7 Services - Fast & Reliable",
        rentalsTab: "Tool Rentals",
        creditsTab: "Tool Credits",
        serverTab: "Server Services",
        ordersTab: "Orders History",
        statusPending: "Processing",
        statusAccepted: "Accepted",
        statusRejected: "Rejected",
        searchPlaceholder: "Search for a tool...",
        searchOrdersPlaceholder: "Search by order ID or tool name...",
        searchButton: "Search",
        orderCodeLabel: "Your Order Code:",
        copyCode: "Copy Code",
        rentNow: "Rent Now",
        priceLabel: "Price:",
        currency: "$",
        rights: "All Rights Reserved",
        paymentTitle: "Available Payment Methods",
        vodafone: "Vodafone Cash",
        binance: "Binance (USDT)",
        instapay: "InstaPay",
        paypal: "PayPal",
        copy: "Copy",
        copied: "Copied!",
        selectPayment: "Confirm Rental Details",
        binanceIdLabel: "Pay ID",
        vodafoneNumberLabel: "Transfer Number",
        confirmOrder: "Confirm Order",
        instructionBinance: "Copy ID and complete payment in Binance app",
        instructionVodafone: "Transfer to the number above (+ fees included)",
        instructionInstapay: "Transfer to the InstaPay number above",
        instructionPaypal: "Click the button above to complete payment via PayPal",
        ultraId: "UltraViewer ID",
        ultraPass: "UltraViewer Password",
        anyDeskId: "AnyDesk ID",
        remoteMethod: "Select Remote Tool",
        paymentMethod: "Select Payment Method",
        senderPhonePlaceholder: "Enter the number you transferred from",
        binanceTxPlaceholder: "Enter Transaction ID or Account Name",
        whatsappNumberLabel: "WhatsApp Number (to receive user/pass)",
        whatsappNumberPlaceholder: "Enter your WhatsApp number",
        preOrderAlert: "Note: Please transfer the amount before clicking Confirm Order",
        verifying: "Verifying...",
        waitOwner: "Please wait while the owner confirms the transfer",
        cancelProcess: "Cancel Process",
        accepted: "Order Accepted Successfully!",
        acceptedMsg: "Payment confirmed, processing your order.",
        rejected: "Payment not received, order rejected",
        rejectedMsg: "Please verify the transfer and try again or contact us.",
        backToStore: "Back to Store",
        close: "Close",
        usd: "USD",
        egp: "EGP",
        darkMode: "Dark",
        lightMode: "Light",
        dir: "ltr",
        productLabel: "Product",
        totalUsd: "Total (USD)",
        rateLabel: "Rate",
        quantityLabel: "Quantity",
        emailLabel: "Email",
        snLabel: "Enter SN",
        helpText: "Need help? Contact us on WhatsApp",
        islamicHeader: "In the name of Allah, the Most Gracious, the Most Merciful",
        hero: "SMART",
        heroHighlight: "SOLUTIONS",
        heroSub: "Professional services, software tool rentals, credit recharging, and server services with the best prices and highest quality.",
        festiveGreeting: "May Allah bring it back to us and you with goodness, blessings, and prosperity. Happy Holidays! ❤️",
        homeTab: "Home",
        ordersHistoryTab: "Orders",
        supportTab: "Technical Support",
        adminTab: "Admin Control",
        adminLoginTitle: "Admin Panel Login",
        adminPasswordLabel: "Password",
        adminPasswordPlaceholder: "Enter admin password...",
        adminLoginButton: "Login",
        adminIncorrectPassword: "Incorrect Password!",
        adminLogoutButton: "Logout",
        adminPanelTitle: "Admin Dashboard",
        adminManageProducts: "Manage Tools",
        adminManageOrders: "Manage Orders",
        adminAddProduct: "Add New Tool",
        adminEditProduct: "Edit Tool",
        adminDeleteProduct: "Delete Tool",
        adminProductNameAr: "Tool Name (Arabic)",
        adminProductNameEn: "Tool Name (English)",
        adminProductPrice: "Price (USD)",
        adminProductDuration: "Duration (e.g. 6 hours)",
        adminProductImage: "Image URL",
        adminProductCategory: "Category",
        adminProductAvailable: "Available to customers",
        adminProductUnavailable: "Unavailable currently",
        adminProductStatus: "Availability",
        adminSaveButton: "Save",
        adminCancelButton: "Cancel",
        adminDeleteConfirm: "Are you sure you want to delete this tool?",
        unavailableBadge: "Unavailable"
    }
} as const;
